[atcoder]
submit_via_binary = true # submit via binary by default
use_cross = true # use `cross` instead of `cargo` when generating binaries
binary_column = 80 # maximum column number of generated binary (0 for no wrapping)
update_interval = 1000 # interval time of fetching result (ms)
# specify `strip` command path. NOTE: if you use macOS, you have to install GNU strip and specify its path here.
strip_path = "/usr/local/opt/binutils/bin/strip"

[profile]
# target to use to generate binary
target = "x86_64-unknown-linux-musl"

[profile.release]
lto = true
panic = 'abort'

# dependencies added to new project
[dependencies]
competitive-hpp = "*"

# competitive = { git = "https://github.com/tanakh/competitive-rs.git" }
[project]
# to create `rust-toolchain` file, uncomment this line.
# rustc_version = "1.15.1"
# source code template
template = """
#![allow(non_snake_case)]
use competitive_hpp::prelude::*;

#[fastout]
fn main() {
    input! {
        a: i32,
    }

    println!("{}", a)
}
"""
